/**
 * @packageDocumentation
 *
 * Auth pack that creates Cognito user-management resources and an admin group.
 */
import { createResourcePack } from "../utils";
import { SimpleCFT } from "../SimpleCFT";

/**
 * Optional logical ids for resources generated by {@link addAuth}.
 */
export type UserManagementIds = {
  userPool?: string;
  userPoolClient?: string;
  identityPool?: string;
  authRole?: string;
  unauthRole?: string;
  roleAttachment?: string;
  domain?: string;
  domainRecord?: string;
  baseDomainRecord?: string;
};

type ResolvedUserManagementIds = Required<UserManagementIds>;

const resolveUserManagementIds = (
  baseId: string,
  ids?: UserManagementIds,
): ResolvedUserManagementIds => ({
  userPool: ids?.userPool || baseId,
  userPoolClient: ids?.userPoolClient || `${baseId}Client`,
  identityPool: ids?.identityPool || `${baseId}IdentityPool`,
  authRole: ids?.authRole || `${baseId}AuthRole`,
  unauthRole: ids?.unauthRole || `${baseId}UnauthRole`,
  roleAttachment: ids?.roleAttachment || `${baseId}IdentityPoolRoles`,
  domain: ids?.domain || `${baseId}Domain`,
  domainRecord: ids?.domainRecord || `${baseId}DomainRecord`,
  baseDomainRecord: ids?.baseDomainRecord || `${baseId}BaseDomainRecord`,
});

/**
 * Configuration for the auth pack.
 */
export type AddAuthConfigBase = {
  /**
   * Base id for Cognito resources.
   */
  userManagementId: string;
  /**
   * IAM role name for authenticated users.
   */
  authRoleName: string;
  /**
   * IAM role name for unauthenticated users.
   */
  unauthRoleName: string;
  /**
   * API Gateway REST API id for authenticated access.
   */
  apiCloudFunctionGatewayId: string;
  /**
   * API Gateway stage name for authenticated access.
   */
  apiStageName: string;
  /**
   * Resource id for the admin group.
   */
  adminGroupId: string;
  /**
   * Cognito group name for admins.
   */
  userManagementAdminGroupName: string;
  /**
   * Optional explicit logical ids for generated user-management resources.
   *
   * @example
   * ```ts
   * userManagementIds: {
   *   userPool: "MyUserPool",
   *   userPoolClient: "MyUserPoolClient",
   * }
   * ```
   */
  userManagementIds?: UserManagementIds;
};

/**
 * Configuration for adding auth resources including a user pool domain with
 * callback and logout URLs.
 */
export type AddAuthConfigWithUserPoolDomain = AddAuthConfigBase & {
  /**
   * Enable Cognito Hosted UI/OAuth redirect mode by creating a custom user pool
   * domain plus Route53 records.
   *
   * When enabled, the generated user pool client uses OAuth flows (`code`,
   * `implicit`) and supports callback/logout URL configuration.
   *
   * Defaults to `true`. Set `false` to opt out of Hosted UI resources and use
   * SDK/API-based sign-in flows only.
   */
  enableUserPoolDomain?: true;
  /**
   * Parameter name for the Route53 hosted zone id that owns `domainName`.
   */
  hostedZoneIdParameterName: string;
  /**
   * Parameter name for the base domain used for the auth subdomain.
   */
  domainNameParameterName: string;
  /**
   * ACM certificate resource id (in `us-east-1`) for the Cognito custom
   * domain.
   */
  sslCertificateId: string;
  /**
   * CloudFront distribution resource id used as the base-domain alias target.
   */
  mainCDNCloudFrontId: string;
  /**
   * OAuth callback URLs for Hosted UI/federated redirect flows.
   */
  callbackUrls: any[];
  /**
   * OAuth logout redirect URLs for Hosted UI sign-out.
   */
  logoutUrls: any[];
  /**
   * Supported identity providers for Hosted UI/OAuth flows.
   */
  supportedIdentityProviders?: any[];
};

/**
 * Configuration for adding auth resources without a user pool domain.
 */
export type AddAuthConfigWithoutUserPoolDomain = AddAuthConfigBase & {
  /**
   * Disable Cognito Hosted UI/OAuth redirect configuration.
   */
  enableUserPoolDomain: false;
  hostedZoneIdParameterName?: never;
  domainNameParameterName?: never;
  sslCertificateId?: never;
  mainCDNCloudFrontId?: never;
  callbackUrls?: never;
  logoutUrls?: never;
  supportedIdentityProviders?: never;
};

/**
 * Configuration for {@link addAuth}.
 */
export type AddAuthConfig =
  | AddAuthConfigWithUserPoolDomain
  | AddAuthConfigWithoutUserPoolDomain;

/**
 * Add auth resources including user management and an admin group.
 *
 * @group Resource Packs
 */
export const addAuth = createResourcePack((config: AddAuthConfig) => {
  const {
    userManagementId,
    userManagementIds,
    authRoleName,
    unauthRoleName,
    apiCloudFunctionGatewayId,
    apiStageName,
    adminGroupId,
    userManagementAdminGroupName,
  } = config;
  const resolvedIds = resolveUserManagementIds(
    userManagementId,
    userManagementIds,
  );
  const isUserPoolDomainEnabled = config.enableUserPoolDomain !== false;
  const supportedIdentityProviders =
    isUserPoolDomainEnabled &&
    "supportedIdentityProviders" in config &&
    config.supportedIdentityProviders &&
    config.supportedIdentityProviders.length > 0
      ? config.supportedIdentityProviders
      : ["COGNITO"];
  const apiRoleConfig: any = {
    [resolvedIds.roleAttachment]: {
      Type: "AWS::Cognito::IdentityPoolRoleAttachment",
      Properties: {
        IdentityPoolId: {
          Ref: resolvedIds.identityPool,
        },
        Roles: {
          authenticated: {
            "Fn::GetAtt": [resolvedIds.authRole, "Arn"],
          },
          unauthenticated: {
            "Fn::GetAtt": [resolvedIds.unauthRole, "Arn"],
          },
        },
      },
    },
    [resolvedIds.authRole]: {
      Type: "AWS::IAM::Role",
      Properties: {
        RoleName: authRoleName,
        Path: "/",
        AssumeRolePolicyDocument: {
          Version: "2012-10-17",
          Statement: [
            {
              Effect: "Allow",
              Principal: {
                Federated: "cognito-identity.amazonaws.com",
              },
              Action: ["sts:AssumeRoleWithWebIdentity"],
              Condition: {
                StringEquals: {
                  "cognito-identity.amazonaws.com:aud": {
                    Ref: resolvedIds.identityPool,
                  },
                },
                "ForAnyValue:StringLike": {
                  "cognito-identity.amazonaws.com:amr": "authenticated",
                },
              },
            },
          ],
        },
        Policies: [
          {
            PolicyName: "CognitoAuthorizedPolicy",
            PolicyDocument: {
              Version: "2012-10-17",
              Statement: [
                {
                  Effect: "Allow",
                  Action: [
                    "mobileanalytics:PutEvents",
                    "cognito-sync:*",
                    "cognito-identity:*",
                  ],
                  Resource: "*",
                },
                {
                  Effect: "Allow",
                  Action: ["execute-api:Invoke"],
                  Resource: {
                    "Fn::Sub": [
                      "arn:aws:execute-api:${Region}:${AccountId}:${APIID}/${StageName}/${HTTPVerb}/api/*",
                      {
                        Region: {
                          Ref: "AWS::Region",
                        },
                        AccountId: {
                          Ref: "AWS::AccountId",
                        },
                        APIID: {
                          Ref: apiCloudFunctionGatewayId,
                        },
                        StageName: apiStageName,
                        HTTPVerb: "*",
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
    [resolvedIds.unauthRole]: {
      Type: "AWS::IAM::Role",
      Properties: {
        RoleName: unauthRoleName,
        Path: "/",
        AssumeRolePolicyDocument: {
          Version: "2012-10-17",
          Statement: [
            {
              Effect: "Allow",
              Principal: {
                Federated: "cognito-identity.amazonaws.com",
              },
              Action: ["sts:AssumeRoleWithWebIdentity"],
              Condition: {
                StringEquals: {
                  "cognito-identity.amazonaws.com:aud": {
                    Ref: resolvedIds.identityPool,
                  },
                },
                "ForAnyValue:StringLike": {
                  "cognito-identity.amazonaws.com:amr": "unauthenticated",
                },
              },
            },
          ],
        },
        Policies: [
          {
            PolicyName: "CognitoUnauthorizedPolicy",
            PolicyDocument: {
              Version: "2012-10-17",
              Statement: [
                {
                  Effect: "Allow",
                  Action: [
                    "mobileanalytics:PutEvents",
                    "cognito-sync:*",
                    "cognito-identity:*",
                  ],
                  Resource: "*",
                },
              ],
            },
          },
        ],
      },
    },
  };

  const userPoolDomainConfig: any =
    config.enableUserPoolDomain === false
      ? {}
      : {
          [resolvedIds.baseDomainRecord]: {
            Type: "AWS::Route53::RecordSet",
            DeletionPolicy: "Delete",
            Properties: {
              HostedZoneId: {
                Ref: config.hostedZoneIdParameterName,
              },
              Type: "A",
              Name: {
                Ref: config.domainNameParameterName,
              },
              AliasTarget: {
                HostedZoneId: "Z2FDTNDATAQYW2",
                DNSName: {
                  "Fn::GetAtt": [config.mainCDNCloudFrontId, "DomainName"],
                },
              },
            },
          },
          [resolvedIds.domainRecord]: {
            Type: "AWS::Route53::RecordSet",
            DeletionPolicy: "Delete",
            Properties: {
              HostedZoneId: {
                Ref: config.hostedZoneIdParameterName,
              },
              Type: "A",
              Name: {
                "Fn::Sub": [
                  "auth.${BaseDomainName}",
                  {
                    BaseDomainName: {
                      Ref: config.domainNameParameterName,
                    },
                  },
                ],
              },
              AliasTarget: {
                HostedZoneId: "Z2FDTNDATAQYW2",
                DNSName: {
                  "Fn::GetAtt": [resolvedIds.domain, "CloudFrontDistribution"],
                },
              },
            },
          },
          [resolvedIds.domain]: {
            Type: "AWS::Cognito::UserPoolDomain",
            DependsOn: resolvedIds.baseDomainRecord,
            Properties: {
              Domain: {
                "Fn::Sub": [
                  "auth.${BaseDomainName}",
                  {
                    BaseDomainName: {
                      Ref: config.domainNameParameterName,
                    },
                  },
                ],
              },
              UserPoolId: {
                Ref: resolvedIds.userPool,
              },
              CustomDomainConfig: {
                CertificateArn: {
                  Ref: config.sslCertificateId,
                },
              },
            },
          },
        };

  const callbackUrls =
    config.enableUserPoolDomain === false ? undefined : config.callbackUrls;
  const logoutUrls =
    config.enableUserPoolDomain === false ? undefined : config.logoutUrls;

  return new SimpleCFT()
    .patch({
      Resources: {
        [resolvedIds.userPool]: {
          Type: "AWS::Cognito::UserPool",
          Properties: {
            UserPoolName: {
              "Fn::Sub": [`$\{AWS::StackName\}${userManagementId}`, {}],
            },
            AccountRecoverySetting: {
              RecoveryMechanisms: [
                {
                  Name: "verified_email",
                  Priority: 1,
                },
              ],
            },
            AdminCreateUserConfig: {
              AllowAdminCreateUserOnly: false,
              UnusedAccountValidityDays: 365,
            },
            AutoVerifiedAttributes: ["email"],
            AliasAttributes: ["phone_number", "email", "preferred_username"],
            Schema: [
              {
                Name: "email",
                Required: true,
                Mutable: true,
              },
              {
                Name: "given_name",
                Required: true,
                Mutable: true,
              },
              {
                Name: "family_name",
                Required: true,
                Mutable: true,
              },
              {
                Name: "phone_number",
                Required: true,
                Mutable: true,
              },
            ],
            DeviceConfiguration: {
              ChallengeRequiredOnNewDevice: true,
              DeviceOnlyRememberedOnUserPrompt: false,
            },
            UsernameConfiguration: {
              CaseSensitive: false,
            },
          },
        },
        [resolvedIds.userPoolClient]: {
          Type: "AWS::Cognito::UserPoolClient",
          Properties: {
            ClientName: {
              "Fn::Sub": [`$\{AWS::StackName\}${userManagementId}Client`, {}],
            },
            UserPoolId: {
              Ref: resolvedIds.userPool,
            },
            ...(isUserPoolDomainEnabled
              ? {
                  AllowedOAuthFlowsUserPoolClient: true,
                  AllowedOAuthFlows: ["code", "implicit"],
                  AllowedOAuthScopes: [
                    "openid",
                    "email",
                    "phone",
                    "profile",
                    "aws.cognito.signin.user.admin",
                  ],
                  SupportedIdentityProviders: supportedIdentityProviders,
                }
              : {
                  AllowedOAuthFlowsUserPoolClient: false,
                }),
            EnableTokenRevocation: true,
            PreventUserExistenceErrors: "ENABLED",
            ...(callbackUrls && callbackUrls.length > 0
              ? { CallbackURLs: callbackUrls }
              : {}),
            ...(logoutUrls && logoutUrls.length > 0
              ? { LogoutURLs: logoutUrls }
              : {}),
          },
        },
        [resolvedIds.identityPool]: {
          Type: "AWS::Cognito::IdentityPool",
          Properties: {
            IdentityPoolName: {
              "Fn::Sub": [
                `$\{AWS::StackName\}${userManagementId}IdentityPool`,
                {},
              ],
            },
            AllowUnauthenticatedIdentities: false,
            CognitoIdentityProviders: [
              {
                ClientId: {
                  Ref: resolvedIds.userPoolClient,
                },
                ProviderName: {
                  "Fn::GetAtt": [resolvedIds.userPool, "ProviderName"],
                },
                ServerSideTokenCheck: true,
              },
            ],
          },
        },
        ...userPoolDomainConfig,
        ...apiRoleConfig,
        [adminGroupId]: {
          Type: "AWS::Cognito::UserPoolGroup",
          Properties: {
            GroupName: userManagementAdminGroupName,
            UserPoolId: {
              Ref: resolvedIds.userPool,
            },
            Description: "Application admin group.",
          },
        },
      },
    }).template;
});
