export type AppConfig = {
  APP_DOMAIN: string;
  API_DOMAIN: string;
  USER_POOL_CLIENT_COOKIE_DOMAIN: string;
  USER_POOL_CLIENT_ID: string;
  OAUTH_CONFIG_DOMAIN: string;
  USER_POOL_CLIENT_DOMAIN: string;
  USER_POOL_CLIENT_CALLBACK_URL: string;
  USER_POOL_CLIENT_LOGOUT_URL: string;
};

export const APP_CONFIG: AppConfig = {
  APP_DOMAIN: process.env.APP_DOMAIN || '',
  API_DOMAIN: process.env.API_DOMAIN || '',
  USER_POOL_CLIENT_COOKIE_DOMAIN: process.env.USER_POOL_CLIENT_COOKIE_DOMAIN || '',
  USER_POOL_CLIENT_ID: process.env.USER_POOL_CLIENT_ID || '',
  OAUTH_CONFIG_DOMAIN: process.env.OAUTH_CONFIG_DOMAIN || '',
  USER_POOL_CLIENT_DOMAIN: process.env.USER_POOL_CLIENT_DOMAIN || '',
  USER_POOL_CLIENT_CALLBACK_URL: process.env.USER_POOL_CLIENT_CALLBACK_URL || '',
  USER_POOL_CLIENT_LOGOUT_URL: process.env.USER_POOL_CLIENT_LOGOUT_URL || '',
};
